# Generated by Django 5.1.6 on 2025-03-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
