# Generated by Django 5.1.6 on 2025-03-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Bloğa Fotoğraf Ekleyin.'),
        ),
    ]
